USE [GISRW01];
GO

DROP TABLE [SDEADM].[AR_TRANSIT_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_TRANSIT_AAN_SAP]
    FROM [SDEADM].[AR_TRANSIT_pid_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pid = t.pid
;

DELETE FROM [SDEADM].[AR_TRANSIT_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '' OR ARCODE LIKE '';

SELECT * FROM [SDEADM].[AR_TRANSIT_AAN_SAP];
