USE [GISRW01];
GO

DROP TABLE [SDEADM].[AR_TRANSIT_CONDO_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
    INTO [SDEADM].[AR_TRANSIT_CONDO_AAN_SAP]
    FROM [SDEADM].[AR_TRANSIT_CONDO_in_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pidrelate = t.pid
;

DELETE FROM [SDEADM].[AR_TRANSIT_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '' OR ARCODE IS NULL OR ARCODE LIKE '';

SELECT * FROM [SDEADM].[AR_TRANSIT_CONDO_AAN_SAP];