USE [GISRW01]
GO

-- PID SAP
IF OBJECT_ID('[SDEADM].[AR_COM_NEW_pid_SAP]', 'U') IS NOT NULL
DROP TABLE [SDEADM].[AR_COM_NEW_pid_SAP];

SELECT
    pid, MIN(AREARATE_CODE) AS ARCODE, MAX(shape_area) AS AREA
    INTO [SDEADM].[AR_COM_NEW_pid_SAP]
    FROM (
        SELECT
            pid,
            AREARATE_CODE,
            shape_area,
            ROW_NUMBER() OVER (PARTITION BY pid ORDER BY shape_area DESC) AS rn
        FROM [SDEADM].[SAP_ComFac_new]
    ) AS subquery
        WHERE rn = 1
        GROUP BY pid
        HAVING MIN(AREARATE_CODE) IS NOT NULL
;

-- AAN SAP
IF OBJECT_ID('[SDEADM].[AR_COM_NEW_AAN_SAP]', 'U') IS NOT NULL
DROP TABLE [SDEADM].[AR_COM_NEW_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) AS ACCTNO, u.PID, u.arcode
    INTO [SDEADM].[AR_COM_NEW_AAN_SAP]
    FROM [SDEADM].[AR_COM_NEW_pid_SAP] u
    JOIN [SDEADM].[LINNS_PIDAANTAX] t ON u.pid = t.pid
;

DELETE FROM [SDEADM].[AR_COM_NEW_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- CONDO IN SAP
IF OBJECT_ID('[SDEADM].[AR_COM_NEW_CONDO_in_SAP]', 'U') IS NOT NULL
DROP TABLE [SDEADM].[AR_COM_NEW_CONDO_in_SAP];

SELECT t.PID, t.PIDRELATE, t.RELNAME, u.arcode
    INTO [SDEADM].[AR_COM_NEW_CONDO_in_SAP]
    FROM [SDEADM].[AR_COM_NEW_pid_SAP] u, [SDEADM].[linns_pidrelate] t
    WHERE u.pid = t.pid
    and t.RELNAME = 'CONDO COMMON PARCEL'
;

-- CONDO AAN SAP
IF OBJECT_ID('[SDEADM].[AR_COM_NEW_CONDO_AAN_SAP]', 'U') IS NOT NULL
DROP TABLE [SDEADM].[AR_COM_NEW_CONDO_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
    INTO [SDEADM].[AR_COM_NEW_CONDO_AAN_SAP]
    FROM [SDEADM].[AR_COM_NEW_CONDO_in_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pidrelate = t.pid;

DELETE FROM [SDEADM].[AR_COM_NEW_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- FINAL SAP
IF OBJECT_ID('[SDEADM].[AR_COM_NEW_FINAL_SAP]', 'U') IS NOT NULL
DROP TABLE [SDEADM].[AR_COM_NEW_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_COM_NEW_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);

INSERT INTO [SDEADM].[AR_COM_NEW_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
        SELECT PID, ACCTNO, ARCODE
        FROM [SDEADM].[AR_COM_NEW_AAN_SAP];

INSERT INTO [SDEADM].[AR_COM_NEW_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
        SELECT PIDRELATE, ACCTNO, ARCODE
        FROM [SDEADM].[AR_COM_NEW_CONDO_AAN_SAP]
;

-- CLEANUP
DROP TABLE AR_COM_NEW_pid_SAP;
DROP TABLE AR_COM_NEW_AAN_SAP;
DROP TABLE AR_COM_NEW_CONDO_in_SAP;
DROP TABLE AR_COM_NEW_CONDO_AAN_SAP;

