USE [GISRW01];
GO

IF OBJECT_ID('[SDEADM].[AR_taxdes_FINAL_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_taxdes_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_taxdes_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);
   
INSERT INTO [SDEADM].[AR_taxdes_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE FROM [SDEADM].[AR_taxdes_AAN_SAP]
       WHERE ACCTNO NOT LIKE '' AND ACCTNO IS NOT NULL AND ARCODE IS NOT NULL AND ARCODE NOT LIKE '';
	   
INSERT INTO [SDEADM].[AR_taxdes_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE FROM [SDEADM].[AR_taxdes_CONDO_AAN_SAP]
       WHERE ACCTNO NOT LIKE '' AND ACCTNO IS NOT NULL AND ARCODE IS NOT NULL AND ARCODE NOT LIKE '';
	   
SELECT * FROM [SDEADM].[AR_taxdes_FINAL_SAP];
