USE [GISRW01];
GO

IF OBJECT_ID('[SDEADM].[AR_taxdes_AAN_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_taxdes_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_taxdes_AAN_SAP]
    FROM [SDEADM].[AR_taxdes_pid_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pid = t.pid;

DELETE FROM [SDEADM].[AR_taxdes_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

SELECT * FROM [SDEADM].[AR_taxdes_AAN_SAP];
