-- Create new table by joining to linns_pidaantax, getting AANs for each PID
-- Remove any records with a null AAN
USE [GISRW01];
GO

IF OBJECT_ID('[SDEADM].[AR_STORMWATER_AAN_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_STORMWATER_AAN_SAP];

SELECT LTRIM(RTRIM(l.AAN)) as "ACCTNO", a.PID, a.arcode
    INTO [SDEADM].[AR_STORMWATER_AAN_SAP]
    FROM [SDEADM].[AR_STORMWATER_pid_SAP] a, [SDEADM].[LINNS_PIDAANTAX] l
    WHERE a.pid = l.pid

DELETE FROM [SDEADM].[AR_STORMWATER_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

SELECT * FROM [SDEADM].[AR_STORMWATER_AAN_SAP];