USE [GISRW01];

IF OBJECT_ID('[SDEADM].[AR_STORMWATER_FINAL_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_STORMWATER_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_STORMWATER_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);
   
INSERT INTO [SDEADM].[AR_STORMWATER_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE
       FROM [SDEADM].[AR_STORMWATER_AAN_SAP]
	   WHERE ACCTNO IS NOT NULL AND ACCTNO NOT LIKE ''
;

INSERT INTO [SDEADM].[AR_STORMWATER_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE
	   FROM [SDEADM].[AR_STORMWATER_CONDO_AAN_SAP]
	   WHERE ACCTNO IS NOT NULL AND ACCTNO NOT LIKE ''
;
	   
SELECT * FROM [SDEADM].[AR_STORMWATER_FINAL_SAP];