-- Get associated AANs for CONDO PIDs
-- Add AANs to AR PID condo table
USE [GISRW01];

IF OBJECT_ID('[SDEADM].[AR_STORMWATER_CONDO_AAN_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_STORMWATER_CONDO_AAN_SAP];

SELECT LTRIM(RTRIM(l.AAN)) as "ACCTNO", a.PIDRELATE, a.pid, a.arcode
    INTO [SDEADM].[AR_STORMWATER_CONDO_AAN_SAP]
    FROM [SDEADM].[AR_STORMWATER_CONDO_in_SAP] a, [SDEADM].[LINNS_PIDAANTAX] l
    WHERE a.pidrelate = l.pid
;

DELETE FROM [SDEADM].[AR_STORMWATER_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

SELECT * FROM [SDEADM].[AR_STORMWATER_CONDO_AAN_SAP];
