-- Combined script generated by ChatGPT on 2025-12-17
-- Source files: ar_PrivRd1_pid_SAP.sql, ar_PrivRd2_AAN_SAP.sql, ar_PrivRd3_CONDO_in_SAP.sql, ar_PrivRd4_CONDO_AAN_SAP.sql, ar_PrivRd5_final_SAP.sql, ar_PrivRd6_clean_SAP.sql

/******************************************************************************
  1) Build PID->ARCODE tables (ar_PrivRd1_pid_SAP.sql)
******************************************************************************/

USE [GISRW01];
GO

DECLARE @tableName VARCHAR(100);
DECLARE @sqlStatement NVARCHAR(MAX);

-- Create a cursor to iterate over the table names
DECLARE tableCursor CURSOR FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'SAP_PRIVRD_R___';  -- Get all tables that start with

-- Open the cursor
OPEN tableCursor;

-- Fetch the first table name
FETCH NEXT FROM tableCursor INTO @tableName;

-- Loop through each table
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'Creating table: AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP';

    -- Generate the dynamic SQL statement
    SET @sqlStatement = N'
    IF OBJECT_ID(''SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP'', ''U'') IS NOT NULL
        DROP TABLE SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP;

    SELECT pid, AREARATE_CODE AS ARCODE
    INTO SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP
    FROM (
        SELECT pid, AREARATE_CODE, shape_area,
               ROW_NUMBER() OVER (
               PARTITION BY pid ORDER BY shape_area DESC
               ) AS rn
        FROM SDEADM.' + QUOTENAME(@tableName) + '
    ) AS subquery
    WHERE rn = 1;

    DELETE FROM SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP
    WHERE arcode IS NULL;

    SELECT * FROM SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP;';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @sqlStatement;

    -- Fetch the next table name
    FETCH NEXT FROM tableCursor INTO @tableName;
END

-- Close and deallocate the cursor
CLOSE tableCursor;
DEALLOCATE tableCursor;

/******************************************************************************
  2) Build AAN tables by joining to LINNS_PIDAANTAX (ar_PrivRd2_AAN_SAP.sql)
******************************************************************************/

USE [GISRW01];
GO

-- Create tables AR_PrivRd_AAN_R000_SAP --> AR_PrivRd_AAN_R210_SAP

DECLARE @tableName VARCHAR(100);
DECLARE @sqlStatement NVARCHAR(MAX);

-- Create a cursor to iterate over the table names
DECLARE tableCursor CURSOR FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'SAP_PRIVRD_R___';  -- Get all tables that start with

-- Open the cursor
OPEN tableCursor;

-- Fetch the first table name
FETCH NEXT FROM tableCursor INTO @tableName;

-- Loop through each table
WHILE @@FETCH_STATUS = 0
BEGIN

    PRINT 'Dropping table: SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP';

    -- Generate the dynamic SQL statement
    SET @sqlStatement = '

	IF OBJECT_ID(''SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP'', ''U'') IS NOT NULL
		DROP TABLE SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP;

    SELECT ltrim(rtrim(t.AAN)) as "ACCTNO", u.PID, u.arcode
        INTO SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP
        FROM SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP u, SDEADM.LINNS_PIDAANTAX t
        WHERE u.pid = t.pid;

    DELETE FROM SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP
    WHERE ACCTNO IS NULL;

    SELECT * FROM SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP;';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @sqlStatement;

    -- Fetch the next table name
    FETCH NEXT FROM tableCursor INTO @tableName;
END

-- Close and deallocate the cursor
CLOSE tableCursor;
DEALLOCATE tableCursor;

/******************************************************************************
  3) Find CONDO COMMON PARCEL relationships (ar_PrivRd3_CONDO_in_SAP.sql)
******************************************************************************/

USE [GISRW01];
GO

-- Create tables AR_PrivRd_pid_000_SAP --> AR_PrivRd_pid_210_SAP

DECLARE @tableName VARCHAR(100);
DECLARE @sqlStatement NVARCHAR(MAX);

-- Create a cursor to iterate over the table names
DECLARE tableCursor CURSOR FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'SAP_PRIVRD_R___';  -- Get all tables that start with

-- Open the cursor
OPEN tableCursor;

-- Fetch the first table name
FETCH NEXT FROM tableCursor INTO @tableName;

-- Loop through each table
WHILE @@FETCH_STATUS = 0
BEGIN

    PRINT 'Creating table: SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_in_SAP';

    -- Generate the dynamic SQL statement
    SET @sqlStatement = '
    IF OBJECT_ID(''SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_in_SAP'', ''U'') IS NOT NULL
        DROP TABLE SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_in_SAP;

    SELECT t.PID, t.PIDRELATE, t.RELNAME, u.arcode
        INTO SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_in_SAP
        FROM SDEADM.AR_PrivRd_pid_R' + RIGHT(@tableName, 3) + '_SAP u, SDEADM.linns_pidrelate t
        WHERE u.pid = t.pid
        AND t.RELNAME = ''CONDO COMMON PARCEL'';

    SELECT * FROM SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_in_SAP;';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @sqlStatement;

    -- Fetch the next table name
    FETCH NEXT FROM tableCursor INTO @tableName;
END

-- Close and deallocate the cursor
CLOSE tableCursor;
DEALLOCATE tableCursor;

/******************************************************************************
  4) Build CONDO AAN tables for related PIDs (ar_PrivRd4_CONDO_AAN_SAP.sql)
******************************************************************************/

USE [GISRW01];
GO

-- Create tables AR_PrivRd_R000_CONDO_AAN_SAP --> AR_PrivRd_R210_CONDO_AAN_SAP
DECLARE @tableName VARCHAR(100);
DECLARE @sqlStatement NVARCHAR(MAX);

-- Create a cursor to iterate over the table names
DECLARE tableCursor CURSOR FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'SAP_PRIVRD_R___';  -- Get all tables that start with

-- Open the cursor
OPEN tableCursor;

-- Fetch the first table name
FETCH NEXT FROM tableCursor INTO @tableName;

-- Loop through each table
WHILE @@FETCH_STATUS = 0
BEGIN

    PRINT 'Creating table: SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_AAN_SAP';

    -- Generate the dynamic SQL statement
    SET @sqlStatement = '
    IF OBJECT_ID(''SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_AAN_SAP'', ''U'') IS NOT NULL
        DROP TABLE SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_AAN_SAP;

    SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
        INTO SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_AAN_SAP
        FROM SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_in_SAP u, SDEADM.LINNS_PIDAANTAX t
        WHERE u.pidrelate = t.pid;

    DELETE FROM SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_AAN_SAP
    WHERE ACCTNO IS NULL;

    SELECT * FROM SDEADM.AR_PrivRd_R' + RIGHT(@tableName, 3) + '_CONDO_AAN_SAP;';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @sqlStatement;

    -- Fetch the next table name
    FETCH NEXT FROM tableCursor INTO @tableName;
END

-- Close and deallocate the cursor
CLOSE tableCursor;
DEALLOCATE tableCursor;

/******************************************************************************
  5) Build FINAL table and insert from AR_PrivRd_AAN_R###_SAP tables (ar_PrivRd5_final_SAP.sql, patched to drop-if-exists)
******************************************************************************/

USE [GISRW01];
GO
IF OBJECT_ID('SDEADM.AR_PrivRd_FINAL_SAP', 'U') IS NOT NULL
    DROP TABLE [SDEADM].[AR_PrivRd_FINAL_SAP];
CREATE TABLE [SDEADM].[AR_PrivRd_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);

--------------------------------------------------------------

-- Create tables AR_PrivRd_pid_000_SAP --> AR_PrivRd_pid_210_SAP

DECLARE @tableName VARCHAR(100);
DECLARE @sqlStatement NVARCHAR(MAX);

-- Create a cursor to iterate over the table names
DECLARE tableCursor CURSOR FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'SAP_PRIVRD_R___';  -- Get all tables that start with

-- Open the cursor
OPEN tableCursor;

-- Fetch the first table name
FETCH NEXT FROM tableCursor INTO @tableName;

-- Loop through each table
WHILE @@FETCH_STATUS = 0
BEGIN

    -- Generate the dynamic SQL statement
    SET @sqlStatement = '

	SELECT * FROM SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP;
	
    INSERT INTO SDEADM.AR_PrivRd_FINAL_SAP
           (PID, ACCTNO, ARCODE)
           SELECT PID, ACCTNO, ARCODE FROM SDEADM.AR_PrivRd_AAN_R' + RIGHT(@tableName, 3) + '_SAP;';

    -- Execute the dynamic SQL statement
    EXEC sp_executesql @sqlStatement;

    -- Fetch the next table name
    FETCH NEXT FROM tableCursor INTO @tableName;
END

-- Close and deallocate the cursor
CLOSE tableCursor;
DEALLOCATE tableCursor;


/******************************************************************************
  6) Optional cleanup of intermediate tables (based on ar_PrivRd6_clean_SAP.sql, made safe)
******************************************************************************/

/*
    Set @DO_CLEANUP = 1 to drop intermediate tables created by steps 1-4.
    Set @DO_CLEANUP = 0 to keep them for QA/debugging.
*/
USE [GISRW01];
GO

DECLARE @DO_CLEANUP bit = 1;
IF @DO_CLEANUP = 1
BEGIN
    -- Drop intermediate tables (IF EXISTS)
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R000_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R000_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R010_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R010_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R020_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R020_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R030_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R030_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R040_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R040_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R050_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R050_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R060_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R060_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R070_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R070_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R080_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R080_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R090_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R090_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R100_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R100_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R110_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R110_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R120_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R120_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R130_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R130_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R140_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R140_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R150_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R150_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R160_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R160_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R170_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R170_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R180_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R180_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R190_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R190_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_pid_R200_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_pid_R200_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R000_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R000_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R010_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R010_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R020_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R020_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R030_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R030_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R040_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R040_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R050_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R050_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R060_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R060_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R070_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R070_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R080_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R080_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R090_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R090_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R100_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R100_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R110_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R110_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R120_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R120_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R130_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R130_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R140_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R140_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R150_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R150_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R160_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R160_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R170_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R170_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R180_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R180_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R190_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R190_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_AAN_R200_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_AAN_R200_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R000_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R000_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R010_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R010_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R020_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R020_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R030_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R030_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R040_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R040_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R050_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R050_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R060_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R060_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R070_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R070_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R080_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R080_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R090_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R090_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R100_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R100_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R110_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R110_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R120_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R120_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R130_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R130_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R140_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R140_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R150_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R150_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R160_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R160_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R170_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R170_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R180_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R180_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R190_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R190_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R200_CONDO_in_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R200_CONDO_in_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R000_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R000_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R010_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R010_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R020_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R020_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R030_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R030_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R040_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R040_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R050_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R050_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R060_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R060_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R070_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R070_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R080_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R080_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R090_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R090_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R100_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R100_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R110_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R110_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R120_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R120_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R130_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R130_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R140_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R140_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R150_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R150_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R160_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R160_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R170_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R170_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R180_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R180_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R190_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R190_CONDO_AAN_SAP];
    IF OBJECT_ID('SDEADM.AR_PrivRd_R200_CONDO_AAN_SAP', 'U') IS NOT NULL DROP TABLE [SDEADM].[AR_PrivRd_R200_CONDO_AAN_SAP];
END
GO
