USE [GISRW01];
GO

DECLARE @tableName1 NVARCHAR(100) = 'SDEADM.AR_ACTIVE_TRANS_pid_SAP';
DECLARE @tableName2 NVARCHAR(100) = 'SDEADM.SAP_ACTIVE_TRANS';
DECLARE @sql NVARCHAR(MAX);

BEGIN TRY
    IF OBJECT_ID(@tableName1, 'U') IS NOT NULL
    BEGIN
        SET @sql = 'DROP TABLE ' + @tableName1 + ';';
        EXEC sp_executesql @sql;
        PRINT 'Dropped table: ' + @tableName1;
    END
    ELSE
    BEGIN
        PRINT 'Table does not exist: ' + @tableName1;
    END

    SET @sql = '
        SELECT t2.pid,
               MIN(t2.AREARATE_CODE) AS ARCODE,
               MAX(t2.shape_area) AS AREA
        INTO ' + @tableName1 + '
        FROM (
            SELECT t1.pid,
                   t1.AREARATE_CODE,
                   t1.shape_area,
                   ROW_NUMBER() OVER (PARTITION BY t1.pid ORDER BY t1.shape_area DESC) AS rn
            FROM ' + @tableName2 + ' t1
        ) AS t2
        WHERE t2.rn = 1 AND t2.AREARATE_CODE IS NOT NULL
        GROUP BY t2.pid;';
    EXEC sp_executesql @sql;
    PRINT 'Created table: ' + @tableName1;

    SET @sql = 'SELECT * FROM ' + @tableName1 + ';';
    EXEC (@sql);
    PRINT 'Selected data from table: ' + @tableName1;
END TRY
BEGIN CATCH
    PRINT 'An error occurred: ' + ERROR_MESSAGE();
END CATCH;

-- AAN SAP
IF OBJECT_ID('[SDEADM].[AR_ACTIVE_TRANS_AAN_SAP]', 'U') IS NOT NULL
    DROP TABLE [SDEADM].[AR_ACTIVE_TRANS_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_ACTIVE_TRANS_AAN_SAP]
    FROM [SDEADM].[AR_ACTIVE_TRANS_pid_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pid = t.pid;

DELETE FROM [SDEADM].[AR_ACTIVE_TRANS_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- CONDO IN SAP
IF OBJECT_ID('[SDEADM].[AR_ACTIVE_TRANS_CONDO_in_SAP]', 'U') IS NOT NULL
    DROP TABLE [SDEADM].[AR_ACTIVE_TRANS_CONDO_in_SAP];

SELECT t.PID, t.PIDRELATE, t.RELNAME, u.arcode
    INTO [SDEADM].[AR_ACTIVE_TRANS_CONDO_in_SAP]
    FROM [SDEADM].[AR_ACTIVE_TRANS_pid_SAP] u, [SDEADM].[linns_pidrelate] t
    WHERE u.pid = t.pid
      AND t.RELNAME = 'CONDO COMMON PARCEL';

-- CONDO AAN SAP
IF OBJECT_ID('[SDEADM].[AR_ACTIVE_TRANS_CONDO_AAN_SAP]', 'U') IS NOT NULL
    DROP TABLE [SDEADM].[AR_ACTIVE_TRANS_CONDO_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
    INTO [SDEADM].[AR_ACTIVE_TRANS_CONDO_AAN_SAP]
    FROM [SDEADM].[AR_ACTIVE_TRANS_CONDO_in_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pidrelate = t.pid;

DELETE FROM [SDEADM].[AR_ACTIVE_TRANS_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- FINAL SAP
IF OBJECT_ID('[SDEADM].[AR_ACTIVE_TRANS_FINAL_SAP]', 'U') IS NOT NULL
    DROP TABLE [SDEADM].[AR_ACTIVE_TRANS_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_ACTIVE_TRANS_FINAL_SAP]
(
   PID VARCHAR(8),
   ACCTNO VARCHAR(24),
   ARCODE VARCHAR(4)
);

INSERT INTO [SDEADM].[AR_ACTIVE_TRANS_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE FROM [SDEADM].[AR_ACTIVE_TRANS_AAN_SAP]
       WHERE ACCTNO NOT LIKE '' AND ACCTNO IS NOT NULL AND ARCODE IS NOT NULL AND ARCODE NOT LIKE '';

INSERT INTO [SDEADM].[AR_ACTIVE_TRANS_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE FROM [SDEADM].[AR_ACTIVE_TRANS_CONDO_AAN_SAP]
       WHERE ACCTNO NOT LIKE '' AND ACCTNO IS NOT NULL AND ARCODE IS NOT NULL AND ARCODE NOT LIKE '';

-- CLEANUP
DROP TABLE AR_ACTIVE_TRANS_pid_SAP;
DROP TABLE AR_ACTIVE_TRANS_AAN_SAP;
DROP TABLE AR_ACTIVE_TRANS_CONDO_in_SAP;
DROP TABLE AR_ACTIVE_TRANS_CONDO_AAN_SAP;