USE [GISRW01];
GO

DROP TABLE [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);
   
INSERT INTO [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE FROM [SDEADM].[AR_COM_FAC_SERV_AAN_SAP]
	   WHERE ARCODE IS NOT NULL AND ARCODE NOT LIKE '' AND ACCTNO IS NOT NULL AND ACCTNO NOT LIKE ''
;

INSERT INTO [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE FROM [SDEADM].[AR_COM_FAC_SERV_CONDO_AAN_SAP]
	   WHERE ARCODE IS NOT NULL AND ARCODE NOT LIKE '' AND ACCTNO IS NOT NULL AND ACCTNO NOT LIKE ''
;

SELECT *
FROM [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]