-- PID SAP
--I added an IF condition to check if the table AR_COM_FAC_SERV_pid_SAP exists before dropping it.
--The KEEP (dense_rank first order by shape_area desc) syntax is replaced with a subquery that utilizes ROW_NUMBER()
--function to get the row with the highest shape_area for each pid.
--The SELECT INTO statement is used to create the AR_COM_FAC_SERV_pid_SAP table based on the results of the query.
--The HAVING clause is modified to check if the minimum AREARATE_CODE is not null.
--The MIN() and MAX() functions are used instead of the KEEP syntax.

USE [GISRW01];
GO

IF OBJECT_ID('[SDEADM].[AR_COM_FAC_SERV_pid_SAP]', 'U') IS NOT NULL
DROP TABLE [sdeadm].[AR_COM_FAC_SERV_pid_SAP];

SELECT pid,
       MIN(AREARATE_CODE) AS ARCODE,
       MAX(shape_area) AS AREA
INTO [SDEADM].[AR_COM_FAC_SERV_pid_SAP]
FROM (
    SELECT pid,
           AREARATE_CODE,
           shape_area,
           ROW_NUMBER() OVER (PARTITION BY pid ORDER BY shape_area DESC) AS rn
    FROM [SDEADM].[SAP_ComFac_SERV]
) AS subquery
WHERE rn = 1
GROUP BY pid
HAVING MIN(AREARATE_CODE) IS NOT NULL;

DELETE FROM [SDEADM].[AR_COM_FAC_SERV_pid_SAP]
WHERE ARCODE IS NULL OR ARCODE LIKE ''

-- AAN SAP
IF OBJECT_ID('[SDEADM].[AR_COM_FAC_SERV_AAN_SAP]', 'U') IS NOT NULL
DROP TABLE [SDEADM].[AR_COM_FAC_SERV_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_COM_FAC_SERV_AAN_SAP]
    FROM [SDEADM].[AR_COM_FAC_SERV_pid_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pid = t.pid
;

DELETE FROM [SDEADM].[AR_COM_FAC_SERV_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- CONDO IN SAP
IF OBJECT_ID('[SDEADM].[AR_COM_FAC_SERV_CONDO_in_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_COM_FAC_SERV_CONDO_in_SAP];

SELECT t.PID, t.PIDRELATE, t.RELNAME, u.arcode
INTO [SDEADM].[AR_COM_FAC_SERV_CONDO_in_SAP]
FROM [SDEADM].[AR_COM_FAC_SERV_pid_SAP] u, [SDEADM].linns_pidrelate t
WHERE u.pid = t.pid
and t.RELNAME = 'CONDO COMMON PARCEL';

-- CONDO AAN SAP 
IF OBJECT_ID('[SDEADM].[AR_COM_FAC_SERV_CONDO_AAN_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_COM_FAC_SERV_CONDO_AAN_SAP];

SELECT trim(t.AAN) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
INTO [SDEADM].[AR_COM_FAC_SERV_CONDO_AAN_SAP]
FROM [SDEADM].[AR_COM_FAC_SERV_CONDO_in_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
WHERE u.pidrelate = t.pid;

DELETE FROM [SDEADM].[AR_COM_FAC_SERV_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- AAN SAP
IF OBJECT_ID('[SDEADM].[AR_COM_FAC_SERV_AAN_SAP]', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_COM_FAC_SERV_AAN_SAP];

SELECT LTRIM(RTRIM(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_COM_FAC_SERV_AAN_SAP]
    FROM [SDEADM].[AR_COM_FAC_SERV_pid_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pid = t.pid
;

DELETE FROM [SDEADM].[AR_COM_FAC_SERV_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- FINAL SAP
DROP TABLE [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);
   
INSERT INTO [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE FROM [SDEADM].[AR_COM_FAC_SERV_AAN_SAP]
	   WHERE ARCODE IS NOT NULL AND ARCODE NOT LIKE '' AND ACCTNO IS NOT NULL AND ACCTNO NOT LIKE ''
;

INSERT INTO [SDEADM].[AR_COM_FAC_SERV_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE FROM [SDEADM].[AR_COM_FAC_SERV_CONDO_AAN_SAP]
	   WHERE ARCODE IS NOT NULL AND ARCODE NOT LIKE '' AND ACCTNO IS NOT NULL AND ACCTNO NOT LIKE ''
;

-- CLEANUP
DROP TABLE AR_COM_FAC_SERV_pid_SAP;
DROP TABLE AR_COM_FAC_SERV_AAN_SAP;
DROP TABLE AR_COM_FAC_SERV_CONDO_in_SAP;
DROP TABLE AR_COM_FAC_SERV_CONDO_AAN_SAP;
