USE [GISRW01];
GO

DROP TABLE [SDEADM].[AR_BID_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_BID_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);

INSERT INTO [SDEADM].[AR_BID_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE FROM [SDEADM].[AR_bid_AAN_SAP]
;
	   
INSERT INTO [SDEADM].[AR_BID_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE FROM [SDEADM].[AR_bid_CONDO_AAN_SAP]
;

SELECT *
FROM [SDEADM].[AR_BID_FINAL_SAP];
