USE [GISRW01];
GO

DROP TABLE [SDEADM].[AR_FIRE_AAN_SAP];

SELECT ltrim(trim(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_FIRE_AAN_SAP]
    FROM [SDEADM].[AR_FIRE_pid_SAP] u
    JOIN [SDEADM].[LINNS_PIDAANTAX] t
        on u.pid = t.pid;

DELETE FROM [SDEADM].[AR_FIRE_AAN_SAP]
WHERE ACCTNO IS NULL or ACCTNO LIKE '';

SELECT * FROM [SDEADM].[AR_FIRE_AAN_SAP];

