USE [GISRW01];
GO

DELETE a
FROM [SDEADM].[AR_FIRE_FINAL_SAP] a
WHERE EXISTS (
    SELECT z.acctno
    FROM [SDEADM].[AR_FIRE_WORSHIP_EXEMPT] z
    WHERE a.acctno = z.acctno
);

SELECT * FROM [SDEADM].[AR_FIRE_FINAL_SAP];