USE [GISRW01];
GO

DROP TABLE [SDEADM].[AR_FIRE_CONDO_AAN_SAP];

SELECT ltrim(rtrim(t.AAN)) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
    INTO [SDEADM].[AR_FIRE_CONDO_AAN_SAP]
    FROM [SDEADM].[AR_FIRE_CONDO_in_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pidrelate = t.pid

DELETE FROM [SDEADM].[AR_FIRE_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

SELECT * FROM [SDEADM].[AR_FIRE_CONDO_AAN_SAP];
