USE [GISRW01];
GO

-- PID SAP
-- Drop the table if it exists
IF OBJECT_ID('sdeadm.AR_Fire_pid_SAP', 'U') IS NOT NULL
    DROP TABLE sdeadm.AR_Fire_pid_SAP;
GO

-- Create the table using SELECT INTO syntax
;WITH MaxShapeAreas AS (
    SELECT 
        pid, 
        AREARATE_CODE AS ARCODE,
        shape_area,
        ROW_NUMBER() OVER (PARTITION BY pid ORDER BY shape_area DESC) AS rn
    FROM sdeadm.SAP_FIRE_PROTECTION
)
SELECT pid, ARCODE
INTO sdeadm.AR_Fire_pid_SAP
FROM MaxShapeAreas
WHERE rn = 1;
	   
-- Delete rows where arcode is NULL
DELETE FROM sdeadm.AR_Fire_pid_SAP
WHERE arcode IS NULL or ARCODE like '';

-- AAN SAP
IF OBJECT_ID('sdeadm.AR_FIRE_AAN_SAP', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_FIRE_AAN_SAP];

SELECT ltrim(trim(t.AAN)) as "ACCTNO", u.PID, u.arcode
    INTO [SDEADM].[AR_FIRE_AAN_SAP]
    FROM [SDEADM].[AR_FIRE_pid_SAP] u
    JOIN [SDEADM].[LINNS_PIDAANTAX] t
        on u.pid = t.pid;

DELETE FROM [SDEADM].[AR_FIRE_AAN_SAP]
WHERE ACCTNO IS NULL or ACCTNO LIKE '';

-- CONDO IN SAP
IF OBJECT_ID('sdeadm.AR_FIRE_CONDO_in_SAP', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_FIRE_CONDO_in_SAP];

SELECT t.PID, t.PIDRELATE, t.RELNAME, u.arcode
    INTO [SDEADM].[AR_FIRE_CONDO_in_SAP]
    FROM [SDEADM].[AR_FIRE_pid_SAP] u, [SDEADM].[linns_pidrelate] t
    WHERE u.pid = t.pid
    and t.RELNAME = 'CONDO COMMON PARCEL'
;

-- CONDO AAN SAP
IF OBJECT_ID('sdeadm.AR_FIRE_CONDO_AAN_SAP', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_FIRE_CONDO_AAN_SAP];

SELECT ltrim(rtrim(t.AAN)) as "ACCTNO", u.PIDRELATE, u.pid, u.arcode
    INTO [SDEADM].[AR_FIRE_CONDO_AAN_SAP]
    FROM [SDEADM].[AR_FIRE_CONDO_in_SAP] u, [SDEADM].[LINNS_PIDAANTAX] t
    WHERE u.pidrelate = t.pid

DELETE FROM [SDEADM].[AR_FIRE_CONDO_AAN_SAP]
WHERE ACCTNO IS NULL OR ACCTNO LIKE '';

-- FINAL SAP
IF OBJECT_ID('sdeadm.AR_FIRE_FINAL_SAP', 'U') IS NOT NULL
	DROP TABLE [SDEADM].[AR_FIRE_FINAL_SAP];

CREATE TABLE [SDEADM].[AR_FIRE_FINAL_SAP]
(
	   PID VARCHAR(8),
       ACCTNO VARCHAR(24),
       ARCODE VARCHAR(4)
);
   
INSERT INTO [SDEADM].[AR_FIRE_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PID, ACCTNO, ARCODE FROM [SDEADM].[AR_FIRE_AAN_SAP]
;
	   
INSERT INTO [SDEADM].[AR_FIRE_FINAL_SAP]
       (PID, ACCTNO, ARCODE)
       SELECT PIDRELATE, ACCTNO, ARCODE FROM [SDEADM].[AR_FIRE_CONDO_AAN_SAP]
;

-- EXEMPTIONS
DELETE a
FROM [SDEADM].[AR_FIRE_FINAL_SAP] a
WHERE EXISTS (
    SELECT z.acctno
    FROM [SDEADM].[AR_FIRE_WORSHIP_EXEMPT] z
    WHERE a.acctno = z.acctno
);

-- CLEANUP
DROP TABLE AR_FIRE_pid_SAP;
DROP TABLE AR_FIRE_AAN_SAP;
DROP TABLE AR_FIRE_CONDO_in_SAP;
DROP TABLE AR_FIRE_CONDO_AAN_SAP;
